### ISSUE TITLE
Error generate-form-service.js

### ISSUE THREAD

**Issue by beligh-hamdi** [jnwltr/swagger-angular-generator#44]
angular 6.0.2

node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:74
    Object.entries(schema).forEach(([paramName, param]) => {
           ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at walkParamOrProp (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:74:12)
    at makeField (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:115:24)
    at Object.entries.forEach (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:85:33)
    at Array.forEach (<anonymous>)
    at walkParamOrProp (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:74:28)
    at makeField (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:115:24)
    at Object.entries.forEach (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:85:33)
    at Array.forEach (<anonymous>)
    at walkParamOrProp (node_modules/swagger-angular-generator/dist/forms/generate-form-service.js:74:28)
npm ERR! code ELIFECYCLE

**Comment by fazpu** [comment]
Please try to install `rxjs-compat`. This repo still uses the RxJS 5 style of imports.

**Comment by jnwltr** [comment]
If it did not help, please, share a relevant part of the schema with us.
