### ISSUE TITLE
Generator fatal error

### ISSUE THREAD

**Issue by MatejBacoOstrov** [jnwltr/swagger-angular-generator#62]
Log:

```
/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/dist/requests/process-paths.js:73
    _.camelCase(method.tags[0].replace(/(-rest)?-controller/, ""))
                           ^

TypeError: Cannot read property '0' of undefined
    at getName (/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/dist/requests/process-paths.js:73:28)
    at _.map (/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/dist/requests/process-paths.js:30:13)
    at /Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:3563:27
    at /Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:3010:24)
    at /Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:4894:18
    at baseMap (/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:3562:7)
    at Function.map (/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:9554:14)
    at _.flatMap (/Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/dist/requests/process-paths.js:28:7)
    at /Users/meldiron/.nvm/versions/node/v8.11.3/lib/node_modules/swagger-angular-generator/node_modules/lodash/lodash.js:3563:27
```

Command: `swagger-angular-generator -s public/swagger.json -d private/swaggerGen`

Swagger json:
```
{
  "swagger": "2.0",
  "schemes": ["http", "https"],
  "host": "localhost:3000",
  "basePath": "/",
  "info": {
    "description": "This is an **example** API to demonstrate features of OpenAPI specification",
    "version": "1.0.0",
    "title": "Example.com",
    "termsOfService": "https://example.com/terms/",
    "contact": {
      "email": "contact@example.com",
      "url": "http://example.com/contact"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "produces": ["application/json"],
  "consumes": ["application/json"],
  "tags": [
    {
      "name": "Echo",
      "description": "Example echo operations"
    }
  ],
  "paths": {
    "/echo": {
      "x-swagger-router-controller": "echoCtrl",
      "get": {
        "tags": ["Echo"],
        "summary": "Echo test",
        "description": "Receive the exact message you've sent",
        "operationId": "getEcho",
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "description": "User name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": ["name", "age"],
              "properties": {
                "name": {
                  "type": "string",
                  "example": "John"
                },
                "age": {
                  "type": "number"
                }
              }
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "type": "object",
              "required": ["status", "message", "error"],
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "error": {}
              }
            }
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "object",
              "required": ["status", "message", "error"],
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "error": {}
              }
            }
          },
          "default": {
            "description": "Default error",
            "schema": {
              "type": "object",
              "required": ["status", "message", "error"],
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "error": {}
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Echo": {
      "type": "object",
      "required": ["name", "age"],
      "properties": {
        "name": {
          "type": "string",
          "example": "John"
        },
        "age": {
          "type": "number"
        }
      }
    }
  }
}

```

**Comment by jnwltr** [comment]
It seems to me it could be caused by `x-swagger-router-controller` method. Is that section intentional? It has no further definition, and hence does not seem to be method at all.
